version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    env_file:
      - credentials.env
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-log-at-trx-commit=0
    environment:
      TZ: 'America/Edmonton'
    ports:
      - 3306:3306